### ISSUE TITLE
When I realize my metadata it isn't preventing me from taking it out infinitely.

### ISSUE THREAD

**Issue by ThePiercedPrince** [11matt556/DSP-ReusableMetadata#1]
I just used your mod for the first time on a brand new game.  And when I opened up meta and did the realization thing, it didn't reset my numbers.  So I am capable of taking out infinite metadata.  I've got about 2.3k blue but just pulled 8k out of the system.  I have tested this with only your mod and bepin-ex, I am using the latest version of DSP and your mod+bepin.   

I was under the impression with this mod that the metadata was supposed to be available up to the point you have gathered it, for the save you are playing.   And then if you play a new game you still have all of the metadata available.  

If you need any assistance in troubleshooting, feel free to ask. I have a lot of experience with troubleshooting and making mods cooperate in games.

Edited to add the log file, which does mention this mod
 
Another update, when I removed your mod, it says I now have -7kish blue metadata.  Because your mod allowed me to use 10k when I didn't have it available.  I'm not mad, just letting you know what's up. 

Re-installing the mod, I get my Metadata availability back though.  Weird.
[output_log.txt](https://github.com/11matt556/DSP-ReusableMetadata/files/8776283/output_log.txt)

**Comment by 11matt556** [comment]
Sorry for the **very** late response. GitHub emails were getting caught in my spam filter so I only just saw this issue.

> So I am capable of taking out infinite metadata. I've got about 2.3k blue but just pulled 8k out of the system. I have tested this with only your mod and bepin-ex, I am using the latest version of DSP and your mod+bepin.

From the output log, it looks like the mod failed to subtract the metadata because it was given a string that cannot be converted to a number. Not sure exactly why it isn't being given a valid number/string, but I found a much better way to get the data that should always be a number. Hopefully I'll have time to put an update together soon.

> Another update, when I removed your mod, it says I now have -7kish blue metadata. Because your mod allowed me to use 10k when I didn't have it available. I'm not mad, just letting you know what's up.
>
> Re-installing the mod, I get my Metadata availability back though. Weird.

It is weird but makes sense based on the way the game handles the metadata property file. I think I know why it is happening but the only way I can think to fix it involves re-implementing the property file, which is a lot deeper/more involved than what I've done so far.

**Comment by 11matt556** [comment]
Version 1.0.5 that I just pushed to the Thunderstore should hopefully fix this issue. I wasn't able to replicate it myself though so let me know if you get a chance to test it.

**Comment by 11matt556** [comment]
Closing since this _should_ be fixed in 1.0.5 and I haven't heard back. Let me know if you still have any problems.
