### ISSUE TITLE
Debug feature: Metadata in Sandbox mode is not working fully

### ISSUE THREAD

**Issue by VTrista** [11matt556/DSP-ReusableMetadata#3]
Hello, I just wanted to inform of two issues that I found when I tried using the debug feature "enableSandboxCheat"

1. It doesn't change the metadata multiplier of already existing sandbox save files, the multiplier staying at 0%.
2. Even new save files in sandbox mode don't allow the generation of metadata, because the game outright ignores the metadata multiplier if the save has been in sandbox mode once.

An extra idea I have: An additional slider, that you can use to change the metadata multiplier for sandbox files to more values between 0% and 400%, or even being part of the multiplier to the main formula for the multiplier calculation.

I hope I can bring these issues into view.

**Comment by VTrista** [comment]
The 2nd issue also only applies to existing sandbox save files. It works properly on new save files.

**Comment by 11matt556** [comment]
I will look into this. From initial investigation I think I see what is wrong so hopefully it is an easy fix.

**Comment by 11matt556** [comment]
So, probably not an easy fix actually. Might be a bit before I can fix this.

**Comment by VTrista** [comment]
Assumed so. I may have no idea on coding, but I assume the function to disable metadata a separate function, which is attached to the save files cluster data, since the game renames the cluster save to have Sxx instead of Axx or Zxx-yy (with xx being the resource multiplier and yy being the combat difficulty rating)

Sadly just editing the metadata multiplier alone doesn't cut it.

I also kinda know why they did that.
If you start a normal game, but then after saving that game once, reload it into sandbox, the metadata multiplier persists.

**Comment by 11matt556** [comment]
Yeah, the sandbox behavior seems to go very deep, since in sandbox mode the functions I use seem to fed values that always result in a 0 metadata available. If I hard-code in a non-zero amount of metadata though I am able to 'realize' the metadata in sandbox mode. But I haven't had any luck figuring out where the zero values are coming from by just looking at the game code. I've overriden all the sandbox checks related to metadata, but it has made no difference. I think I'll probably need to go through and debug the output of all the functions used in the metadata logic until I find the 0 values, since I assume the problematic function must be referencing sandbox mode in some non-obvious or indirect way. I also suspect I may have some unrelated bug, since when debugging this issue I found that Game Contribution and Cluster Contribution seem to be swapped in the UI even though the metadata calculations seem to behave correctly, as if they were not swapped.

**Comment by 11matt556** [comment]
I think I might have it working, but only on games that are created as sandbox from the start, and only with matrix cubes that are generated "legitimately". In other words, spawning matrix cubes with the traffic monitor does not count for metadata, but any created by matrix labs do count.

I think the matrix cube generation is just going to have to be a limitation at the moment, since I don't really want to start messing with the factory production logic (which is mostly separate from metadata stuff).

Need to do some more testing to figure out what the difference is between new and existing games.

**Comment by 11matt556** [comment]
@VTrista: This should now be fixed in the latest 1.0.7 release. Let me know if you run into issues in your game. I also added a config option to adjust the multiplier value to whatever you want.
